name: chat_bot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.12.0
  json_serializable: ^6.12.0
  retrofit: ^4.9.2
  json_annotation: ^4.10.0
  retrofit_generator: ^10.2.1
  build_runner: ^2.10.5
  dia: ^0.1.5
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  shared_preferences: ^2.5.4
  firebase_core: ^4.4.0
  http: ^1.6.0
  dartz: ^0.10.1
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf

