// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjettH81Mm2NNuxLxPqLmWjUXk-JS5d8I',
    appId: '1:65492704218:web:dc952a10f8e926ba793ee3',
    messagingSenderId: '65492704218',
    projectId: 'chat-bot-1991c',
    authDomain: 'chat-bot-1991c.firebaseapp.com',
    storageBucket: 'chat-bot-1991c.firebasestorage.app',
    measurementId: 'G-PXXJJB5D1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHq_51XFO78leHkep3gSDWp5f7_fvd2Jk',
    appId: '1:235587154170:android:ae79f1c5b8603529531943',
    messagingSenderId: '235587154170',
    projectId: 'chatbot-stg-mh',
    storageBucket: 'chatbot-stg-mh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUZEbBA57Zkbwv7bxH-TEvNIDxnYiDt34',
    appId: '1:65492704218:ios:833323e6481726a5793ee3',
    messagingSenderId: '65492704218',
    projectId: 'chat-bot-1991c',
    storageBucket: 'chat-bot-1991c.firebasestorage.app',
    iosBundleId: 'com.example.chatBot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUZEbBA57Zkbwv7bxH-TEvNIDxnYiDt34',
    appId: '1:65492704218:ios:833323e6481726a5793ee3',
    messagingSenderId: '65492704218',
    projectId: 'chat-bot-1991c',
    storageBucket: 'chat-bot-1991c.firebasestorage.app',
    iosBundleId: 'com.example.chatBot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjettH81Mm2NNuxLxPqLmWjUXk-JS5d8I',
    appId: '1:65492704218:web:cf7a4b95b0ba9a85793ee3',
    messagingSenderId: '65492704218',
    projectId: 'chat-bot-1991c',
    authDomain: 'chat-bot-1991c.firebaseapp.com',
    storageBucket: 'chat-bot-1991c.firebasestorage.app',
    measurementId: 'G-LSK463N6TB',
  );
}