name: Firebase App Distribution

on:
  # This workflow is triggered manually via the GitHub Actions UI.
  workflow_dispatch:
jobs:
  android_firebase_app_distribution:
    runs-on: ubuntu-latest

    steps:
      # 1. check out repository
      - name: Checkout code
        uses: actions/checkout@v4
        
      # 2. Java (Android build requirement)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Flutter (stable + cache)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      # 4. Cache Gradle (faster builds 🚀)
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            gradle-${{ runner.os }}

      # 5. Ruby + Fastlane
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          working-directory: android

      - name: preper android signing
        env:
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          working-directory: android

      # 7. Run Fastlane lane
      - name: Run fastlane firebase app distribution
        working-directory: android
        run: bundle exec fastlane distribute_release_to_firebase


  